version: '3'
services:
  appcontainer:
     build:
      context: .
      args:
        JAR_FILE: /garbarino-0.0.1-SNAPSHOT.jar
     restart: always
     ports:
      - "8090:8080"
     links:
       - mongo
     depends_on:
       - mongo
     environment:
       WAIT_HOSTS: mongo:27017
  mongo:
    image: mongo
    container_name: garbarino-mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
