version: "3"
services:
  appcontainer:
    build:
      args:
        JAR_FILE: garbarino-0.0.1-SNAPSHOT.jar
      context: "."
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: "mongo:27017"
    links:
      - mongo
    ports:
      - "8090:8080"
    restart: always
  mongo:
    container_name: garbarino-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db" 
