version: '3'
services:
  appcontainer:
     restart: always
     ports:
      - "8080:8080"
     links:
       - mongo
     depends_on:
       - mongo
     environment:
       WAIT_HOSTS: mongo:27017
  mongo:
    image: mongo
    container_name: garbarino-mongo
    ports:
      - "27017:27017"
